INSERT INTO mundos (nombre, descripcion, orden) VALUES ('Mundo 1: Fundamentos de Python', 'Conceptos básicos de variables, tipos de datos y operadores.', 1);
INSERT INTO mundos (nombre, descripcion, orden) VALUES ('Mundo 2: Control de Flujo', 'Condicionales, bucles y estructuras de control.', 2);
INSERT INTO mundos (nombre, descripcion, orden) VALUES ('Mundo 3: Funciones en Python', 'Definición y uso de funciones, argumentos y retorno.', 3);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (1, 'Tipos de datos', 'Reconocer tipos de datos básicos en Python.', 1);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (1, 'Imprimir en consola', 'Usar la función print().', 2);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (1, 'Asignación de variables', 'Reglas de asignación de variables.', 3);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (1, 'Nombres de variables válidos', 'Identificadores válidos en Python.', 4);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (1, 'Operadores lógicos', 'Uso de operadores lógicos como 'and'.', 5);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (1, 'Comentarios', 'Sintaxis de comentarios en Python.', 6);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (2, 'Condicionales', 'Uso de if y comparadores.', 1);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (2, 'Bucle for', 'Uso básico del bucle for con range.', 2);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (2, 'Bucle while', 'Control de flujo con while y operadores de incremento.', 3);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (2, 'Errores de concatenación', 'Errores al concatenar strings y números.', 4);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (2, 'Listas y acceso por índice', 'Uso de listas y acceso a elementos.', 5);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (2, 'Casting de datos', 'Errores de tipo al mezclar strings y enteros.', 6);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (3, 'Definir funciones', 'Definir y llamar funciones.', 1);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (3, 'Funciones sin argumentos', 'Definir funciones sin argumentos.', 2);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (3, 'Completar definición de función', 'Sintaxis correcta de definición de función.', 3);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (3, 'Argumentos en funciones', 'Uso de parámetros dentro de funciones.', 4);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (3, 'Funciones booleanas', 'Evaluación de funciones que retornan booleanos.', 5);
INSERT INTO lecciones (id_mundo, nombre, descripcion, orden) VALUES (3, 'Parámetros por defecto', 'Uso de argumentos con valores por defecto.', 6);